name: Long Do
run-name: Checking LongDo pull request
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: configurate
        run: cmake -S . --preset ninja-multi
      - name: build
        run: cmake --build --preset release
