name: Long Do
run-name: Checking LongDo pull request
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: ['debug', 'release']
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-environment
      - name: configure
        run: cmake -S . --preset ninja-multi
      - name: build
        run: cmake --build --preset ${{ matrix.build-type }}
  clang_tidy:
    runs-on: ubuntu-latest
    name: "Clang-tidy run"
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-environment
      - name: configure
        run: cmake -S . --preset clang-tidy
      - name: build
        run: cmake --build --preset clang-tidy
  clazy:
    runs-on: ubuntu-latest
    name: "Clazy run"
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-environment
      - run: sudo apt install -y clazy
      - name: configure
        run: cmake -S . --preset clazy
      - name: build
        run: cmake --build --preset clazy
