name: Long Do
run-name: Checking LongDo pull request
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.5.*
      - name: configure
        run: cmake -S . --preset ninja-multi
      - name: build
        run: cmake --build --preset release
  clang_tidy:
    runs-on: ubuntu-latest
    name: "Clang-tidy run"
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.5.*
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: 19
      - name: configure
        run: cmake -S . --preset clang-tidy
      - name: build
        run: cmake --build --preset clang-tidy
